import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  containerDark: { backgroundColor: '#0B132B' },
  scrollContent: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 120 },
  headerContainer: { marginBottom: 14 },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerTitle: { fontSize: 22, fontWeight: '800', color: '#0F172A' },
  headerSubtitle: { fontSize: 13, color: '#64748B', marginTop: 4 },
  textLight: { color: '#F8FAFC' },
  textMuted: { color: '#94A3B8' },
  locationIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#DDF4F7', alignItems: 'center', justifyContent: 'center' },
  mapCard: { height: 480, borderRadius: 16, overflow: 'hidden', backgroundColor: '#DDE7EA', borderWidth: 1, borderColor: '#CBD5E1', position: 'relative' },
  mapCardDark: { backgroundColor: '#0B132B', borderColor: '#3A506B' },
  map: { flex: 1 },
  mapLoading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  mapLoadingText: { color: '#176B87', fontSize: 13, fontWeight: '600' },
  permissionCard: { marginTop: 12, padding: 14, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardDark: { backgroundColor: '#1C2541', borderColor: '#3A506B' },
  permissionCopy: { flex: 1 },
  permissionTitle: { color: '#0F172A', fontWeight: '800', fontSize: 14 },
  permissionText: { color: '#64748B', fontSize: 12, lineHeight: 17, marginTop: 3 },
  permissionButton: { backgroundColor: '#176B87', paddingHorizontal: 14, paddingVertical: 9, borderRadius: 9 },
  permissionButtonText: { color: '#FFFFFF', fontWeight: '800', fontSize: 12 },
  legendOverlay: { position: 'absolute', top: 12, right: 12, width: 225, padding: 12, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.55)', overflow: 'hidden' },
  legendTitle: { color: '#0F172A', fontSize: 13, fontWeight: '800', marginBottom: 9 },
  legendGrid: { rowGap: 8 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendDot: { width: 14, height: 14, borderRadius: 7, borderWidth: 1.5, borderColor: '#FFFFFF' },
  legendText: { color: '#475569', fontSize: 11, flexShrink: 1, fontWeight: '600' },

  // Risk Cards List
  sectionHeader: { marginTop: 20, marginBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: '#0F172A' },
  riskGrid: { gap: 12 },
  riskCard: { padding: 14, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', flexDirection: 'row', alignItems: 'center', gap: 12 },
  riskCardDark: { backgroundColor: '#1C2541', borderColor: '#3A506B' },
  circleBadgeWrapper: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  circleBadgeInner: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: '#FFFFFF', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 3, elevation: 3 },
  riskInfo: { flex: 1 },
  riskHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  riskName: { fontSize: 14, fontWeight: '700', color: '#0F172A' },
  barangayTag: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6, backgroundColor: '#F1F5F9' },
  barangayTagDark: { backgroundColor: '#334155' },
  barangayTagText: { fontSize: 10, fontWeight: '700', color: '#64748B' },
  riskDetail: { fontSize: 12, color: '#64748B', marginTop: 3 },
  badgeColumn: { alignItems: 'flex-end', gap: 4 },
  radiusBadge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 12, backgroundColor: '#F1F5F9' },
  radiusBadgeDark: { backgroundColor: '#334155' },
  radiusText: { fontSize: 11, fontWeight: '700', color: '#475569' },
  casesCountBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, backgroundColor: '#FEF2F2', borderBottomWidth: 1, borderColor: '#FCA5A5' },
  casesCountText: { fontSize: 10, fontWeight: '800' },
});
